name: Test

on:
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{'{'}}{ secrets.NPM_GITHUB_TOKEN }}

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{'{'}}{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm config get cacheFolder)"

      - name: Cache pnpm dependencies
        uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: |
            ${{'{'}}{ steps.pnpm-cache-dir-path.outputs.dir }}
            **\node_modules
          key: ${{'{'}}{ runner.os }}-pnpm-${{'{'}}{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{'{'}}{ runner.os }}-pnpm-

      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Fetch main
        run: git fetch origin main

      - name: Test
        run: |
          RUN=CI pnpm nx affected:test --base=origin/main --parallel 5
          pnpm nx affected:lint --base=origin/main --parallel 5
